In [2]:
import pandas as pd

In [3]:
file_path = "../data/raw/transactions-2026-09-03.csv"

In [4]:
df_sample = pd.read_csv(
    file_path,
    nrows=1000
)

In [5]:
df_sample.shape

(1000, 22)

In [6]:
df_sample.head()

,TRANSACTION_NUMBER,INSTANCE_DATE,GROUP_EN,PROCEDURE_EN,IS_OFFPLAN_EN,IS_FREE_HOLD_EN,USAGE_EN,AREA_EN,PROP_TYPE_EN,PROP_SB_TYPE_EN,...,ACTUAL_AREA,ROOMS_EN,PARKING,NEAREST_METRO_EN,NEAREST_MALL_EN,NEAREST_LANDMARK_EN,TOTAL_BUYER,TOTAL_SELLER,MASTER_PROJECT_EN,PROJECT_EN
0,101-10-2026,2026-07-01 16:00:21,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,46.17,Studio,1,Buj Khalifa Dubai Mall Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,THE CRESTMARK
1,101-10-2026,2026-07-01 16:00:21,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,99.32,1 B/R,1,Buj Khalifa Dubai Mall Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,THE CRESTMARK
2,101-10-2026,2026-07-01 16:00:21,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,91.81,1 B/R,1,Buj Khalifa Dubai Mall Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,THE CRESTMARK
3,101-10-2026,2026-07-01 16:00:21,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,46.15,Studio,1,Buj Khalifa Dubai Mall Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,THE CRESTMARK
4,101-11-2026,2026-07-01 16:29:02,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,Palm Deira,Unit,Shop,...,535.68,NaN,8,NaN,NaN,NaN,0,0,NaN,ELLINGTON SANDS I

In [7]:
df_sample.columns

Index(['TRANSACTION_NUMBER', 'INSTANCE_DATE', 'GROUP_EN', 'PROCEDURE_EN',
       'IS_OFFPLAN_EN', 'IS_FREE_HOLD_EN', 'USAGE_EN', 'AREA_EN',
       'PROP_TYPE_EN', 'PROP_SB_TYPE_EN', 'TRANS_VALUE', 'PROCEDURE_AREA',
       'ACTUAL_AREA', 'ROOMS_EN', 'PARKING', 'NEAREST_METRO_EN',
       'NEAREST_MALL_EN', 'NEAREST_LANDMARK_EN', 'TOTAL_BUYER', 'TOTAL_SELLER',
       'MASTER_PROJECT_EN', 'PROJECT_EN'],
      dtype='str')

In [8]:
df_sample.dtypes

TRANSACTION_NUMBER         str
INSTANCE_DATE              str
GROUP_EN                   str
PROCEDURE_EN               str
IS_OFFPLAN_EN              str
IS_FREE_HOLD_EN            str
USAGE_EN                   str
AREA_EN                    str
PROP_TYPE_EN               str
PROP_SB_TYPE_EN            str
TRANS_VALUE            float64
PROCEDURE_AREA         float64
ACTUAL_AREA            float64
ROOMS_EN                   str
PARKING                    str
NEAREST_METRO_EN           str
NEAREST_MALL_EN            str
NEAREST_LANDMARK_EN        str
TOTAL_BUYER              int64
TOTAL_SELLER             int64
MASTER_PROJECT_EN          str
PROJECT_EN                 str
dtype: object

In [9]:
df_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TRANSACTION_NUMBER   1000 non-null   str
 1   INSTANCE_DATE        1000 non-null   str
 2   GROUP_EN             1000 non-null   str
 3   PROCEDURE_EN         1000 non-null   str
 4   IS_OFFPLAN_EN        1000 non-null   str
 5   IS_FREE_HOLD_EN      1000 non-null   str
 6   USAGE_EN             1000 non-null   str
 7   AREA_EN              1000 non-null   str
 8   PROP_TYPE_EN         1000 non-null   str
 9   PROP_SB_TYPE_EN      1000 non-null   str
 10  TRANS_VALUE          1000 non-null   float64
 11  PROCEDURE_AREA       1000 non-null   float64
 12  ACTUAL_AREA          1000 non-null   float64
 13  ROOMS_EN             956 non-null    str
 14  PARKING              817 non-null    str
 15  NEAREST_METRO_EN     488 non-null    str
 16  NEAREST_MALL_EN      475 non-null    str
 17  NEAREST_LANDMARK_EN  600 non-null    str
 18  TOTAL_BUYER          1000 non-null   int64
 19  TOTAL_SELLER         1000 non-null   int64
 20  MASTER_PROJECT_EN    3 non-null      str
 21  PROJECT_EN           1000 non-null   str
dtypes: float64(3), int64(2), str(17)
memory usage: 172.0 KB

In [10]:
df_sample.describe()

        TRANS_VALUE  PROCEDURE_AREA  ACTUAL_AREA  TOTAL_BUYER  TOTAL_SELLER
count  1.000000e+03     1000.000000  1000.000000       1000.0        1000.0
mean   2.618646e+06      110.163470   110.402090          0.0           0.0
std    4.372980e+06       95.643301    95.597316          0.0           0.0
min    1.566500e+05        3.730000     6.880000          0.0           0.0
25%    8.764992e+05       62.530000    62.530000          0.0           0.0
50%    1.573999e+06       81.650000    81.710000          0.0           0.0
75%    2.825000e+06      130.590000   131.467500          0.0           0.0
max    7.156357e+07     1322.910000  1322.910000          0.0           0.0

In [11]:
df_sample.isna()

,TRANSACTION_NUMBER,INSTANCE_DATE,GROUP_EN,PROCEDURE_EN,IS_OFFPLAN_EN,IS_FREE_HOLD_EN,USAGE_EN,AREA_EN,PROP_TYPE_EN,PROP_SB_TYPE_EN,...,ACTUAL_AREA,ROOMS_EN,PARKING,NEAREST_METRO_EN,NEAREST_MALL_EN,NEAREST_LANDMARK_EN,TOTAL_BUYER,TOTAL_SELLER,MASTER_PROJECT_EN,PROJECT_EN
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,True,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,True,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,True,False

In [12]:
df_sample.isna().sum()

TRANSACTION_NUMBER       0
INSTANCE_DATE            0
GROUP_EN                 0
PROCEDURE_EN             0
IS_OFFPLAN_EN            0
IS_FREE_HOLD_EN          0
USAGE_EN                 0
AREA_EN                  0
PROP_TYPE_EN             0
PROP_SB_TYPE_EN          0
TRANS_VALUE              0
PROCEDURE_AREA           0
ACTUAL_AREA              0
ROOMS_EN                44
PARKING                183
NEAREST_METRO_EN       512
NEAREST_MALL_EN        525
NEAREST_LANDMARK_EN    400
TOTAL_BUYER              0
TOTAL_SELLER             0
MASTER_PROJECT_EN      997
PROJECT_EN               0
dtype: int64

In [13]:
missing_pct = df_sample.isna().mean() * 100

In [14]:
missing_pct

TRANSACTION_NUMBER      0.0
INSTANCE_DATE           0.0
GROUP_EN                0.0
PROCEDURE_EN            0.0
IS_OFFPLAN_EN           0.0
IS_FREE_HOLD_EN         0.0
USAGE_EN                0.0
AREA_EN                 0.0
PROP_TYPE_EN            0.0
PROP_SB_TYPE_EN         0.0
TRANS_VALUE             0.0
PROCEDURE_AREA          0.0
ACTUAL_AREA             0.0
ROOMS_EN                4.4
PARKING                18.3
NEAREST_METRO_EN       51.2
NEAREST_MALL_EN        52.5
NEAREST_LANDMARK_EN    40.0
TOTAL_BUYER             0.0
TOTAL_SELLER            0.0
MASTER_PROJECT_EN      99.7
PROJECT_EN              0.0
dtype: float64

In [15]:
df_sample["GROUP_EN"].value_counts()

GROUP_EN
Sales       795
Mortgage    205
Name: count, dtype: int64

In [16]:
df_sample["PROCEDURE_EN"].value_counts()

PROCEDURE_EN
Sell - Pre registration                             795
Portfolio Mortgage Registration Pre-Registration    205
Name: count, dtype: int64

In [17]:
for column in [
    "IS_OFFPLAN_EN",
    "IS_FREE_HOLD_EN",
    "USAGE_EN",
    "PROP_TYPE_EN",
    "PROP_SB_TYPE_EN"
]:
    print(f"\n--- {column} ---")
    print(df_sample[column].value_counts())

--- IS_OFFPLAN_EN ---
IS_OFFPLAN_EN
Off-Plan    1000
Name: count, dtype: int64

--- IS_FREE_HOLD_EN ---
IS_FREE_HOLD_EN
Free Hold    1000
Name: count, dtype: int64

--- USAGE_EN ---
USAGE_EN
Residential    1000
Name: count, dtype: int64

--- PROP_TYPE_EN ---
PROP_TYPE_EN
Unit        842
Building    158
Name: count, dtype: int64

--- PROP_SB_TYPE_EN ---
PROP_SB_TYPE_EN
Flat               781
Villa              158
Office              35
Hotel Apartment     13
Shop                 9
Hotel Rooms          4
Name: count, dtype: int64

In [18]:
df_sample["PROP_SB_TYPE_EN"].value_counts().to_string()

'PROP_SB_TYPE_EN\nFlat               781\nVilla              158\nOffice              35\nHotel Apartment     13\nShop                 9\nHotel Rooms          4'

In [19]:
df_sample[
    [
        "TRANS_VALUE",
        "PROCEDURE_AREA",
        "ACTUAL_AREA",
        "TOTAL_BUYER",
        "TOTAL_SELLER"
    ]
].describe()

        TRANS_VALUE  PROCEDURE_AREA  ACTUAL_AREA  TOTAL_BUYER  TOTAL_SELLER
count  1.000000e+03     1000.000000  1000.000000       1000.0        1000.0
mean   2.618646e+06      110.163470   110.402090          0.0           0.0
std    4.372980e+06       95.643301    95.597316          0.0           0.0
min    1.566500e+05        3.730000     6.880000          0.0           0.0
25%    8.764992e+05       62.530000    62.530000          0.0           0.0
50%    1.573999e+06       81.650000    81.710000          0.0           0.0
75%    2.825000e+06      130.590000   131.467500          0.0           0.0
max    7.156357e+07     1322.910000  1322.910000          0.0           0.0

In [20]:
df_sample[["TOTAL_BUYER", "TOTAL_SELLER"]].value_counts()

TOTAL_BUYER  TOTAL_SELLER
0            0               1000
Name: count, dtype: int64

In [21]:
df_sample["INSTANCE_DATE"].head(10)

0    2026-07-01 16:00:21
1    2026-07-01 16:00:21
2    2026-07-01 16:00:21
3    2026-07-01 16:00:21
4    2026-07-01 16:29:02
5    2026-07-01 16:29:02
6    2026-07-01 16:29:02
7    2026-07-01 16:29:02
8    2026-07-01 16:12:45
9    2026-07-01 16:12:45
Name: INSTANCE_DATE, dtype: str

In [22]:
df_sample["TRANSACTION_NUMBER"].nunique()

811

In [23]:
df_sample["TRANSACTION_NUMBER"].value_counts().value_counts()

count
1     795
4       4
12      2
6       2
3       2
80      1
27      1
15      1
13      1
7       1
5       1
Name: count, dtype: int64

In [24]:
transaction_counts = df_sample["TRANSACTION_NUMBER"].value_counts()

transaction_counts[transaction_counts > 20]

TRANSACTION_NUMBER
101-3-2026    80
101-6-2026    27
Name: count, dtype: int64

In [25]:
df_sample[df_sample["TRANSACTION_NUMBER"] == "101-3-2026"]

,TRANSACTION_NUMBER,INSTANCE_DATE,GROUP_EN,PROCEDURE_EN,IS_OFFPLAN_EN,IS_FREE_HOLD_EN,USAGE_EN,AREA_EN,PROP_TYPE_EN,PROP_SB_TYPE_EN,...,ACTUAL_AREA,ROOMS_EN,PARKING,NEAREST_METRO_EN,NEAREST_MALL_EN,NEAREST_LANDMARK_EN,TOTAL_BUYER,TOTAL_SELLER,MASTER_PROJECT_EN,PROJECT_EN
48,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,40.03,Studio,NaN,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER
49,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,41.97,Studio,NaN,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER
50,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,40.03,Studio,NaN,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER
51,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,41.97,Studio,NaN,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER
52,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,40.03,Studio,NaN,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,65.98,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER
124,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,40.03,Studio,NaN,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER
125,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,41.97,Studio,NaN,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER
126,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,40.03,Studio,NaN,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER
127,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,41.97,Studio,NaN,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER

In [26]:
df_sample.duplicated().sum()

np.int64(99)

In [27]:
df_sample.drop_duplicates().shape

(901, 22)

In [28]:
df_sample.nunique()

TRANSACTION_NUMBER     811
INSTANCE_DATE          806
GROUP_EN                 2
PROCEDURE_EN             2
IS_OFFPLAN_EN            1
IS_FREE_HOLD_EN          1
USAGE_EN                 1
AREA_EN                 72
PROP_TYPE_EN             2
PROP_SB_TYPE_EN          6
TRANS_VALUE            705
PROCEDURE_AREA         696
ACTUAL_AREA            702
ROOMS_EN                 7
PARKING                 38
NEAREST_METRO_EN        25
NEAREST_MALL_EN          5
NEAREST_LANDMARK_EN     10
TOTAL_BUYER              1
TOTAL_SELLER             1
MASTER_PROJECT_EN        1
PROJECT_EN             271
dtype: int64

In [29]:
df_sample.memory_usage(deep=True).sum()

np.int64(1000274)

In [30]:
with open(file_path, "r", encoding="utf-8") as f:
    row_count = sum(1 for _ in f) - 1

row_count

148625

In [31]:
df = pd.read_csv(file_path)

df.shape

(148591, 22)

In [32]:
df.memory_usage(deep=True).sum() / (1024 ** 2)

np.float64(139.26946258544922)

In [33]:
missing = df.isna().sum()

missing_pct = (df.isna().mean() * 100).round(2)

pd.DataFrame({
    "missing_count": missing,
    "missing_pct": missing_pct
}).sort_values("missing_count", ascending=False)

                     missing_count  missing_pct
MASTER_PROJECT_EN           148066        99.65
NEAREST_MALL_EN              78058        52.53
NEAREST_METRO_EN             76411        51.42
NEAREST_LANDMARK_EN          57790        38.89
PARKING                      32927        22.16
ROOMS_EN                     21126        14.22
PROJECT_EN                   18943        12.75
PROP_SB_TYPE_EN               1886         1.27
PROCEDURE_AREA                   4         0.00
IS_OFFPLAN_EN                    0         0.00
INSTANCE_DATE                    0         0.00
TRANSACTION_NUMBER               0         0.00
PROCEDURE_EN                     0         0.00
GROUP_EN                         0         0.00
IS_FREE_HOLD_EN                  0         0.00
ACTUAL_AREA                      0         0.00
AREA_EN                          0         0.00
PROP_TYPE_EN                     0         0.00
USAGE_EN                         0         0.00
TRANS_VALUE                      0         0.00
TOTAL_SELLER                     0         0.00
TOTAL_BUYER                      0         0.00

In [34]:
categorical_cols = [
    "GROUP_EN",
    "PROCEDURE_EN",
    "IS_OFFPLAN_EN",
    "IS_FREE_HOLD_EN",
    "USAGE_EN",
    "PROP_TYPE_EN",
    "PROP_SB_TYPE_EN"
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- GROUP_EN ---
GROUP_EN
Sales       112033
Mortgage     30658
Gifts         5900
Name: count, dtype: int64

--- PROCEDURE_EN ---
PROCEDURE_EN
Sell - Pre registration                             75147
Sale                                                26033
Mortgage Registration                               20465
Delayed Sell                                         7590
Grant                                                4547
Delayed Mortgage                                     2852
Portfolio Mortgage Registration                      2817
Development Registration Pre-Registration            1468
Modify Mortgage                                      1145
Portfolio Mortgage Modification                      1095
Grant Pre-Registration                                883
Lease to Own Registration                             818
Sell Development                                      703
Development Mortgage                                  469
Lease Finance Registration                            440
Grant on Delayed Sell                                 366
Mortgage Pre-Registration                             328
Development Registration                              273
Sale On Payment Plan                                  261
Portfolio Mortgage Development Registration           224
Portfolio Mortgage Registration Pre-Registration      205
Grant Development                                     104
Delayed Sell Lease to Own Registration                 80
Delayed Development                                    75
Modify Development Mortgage                            59
Portfolio Mortgage Modification Pre-Registration       30
Lease to Own Modify                                    27
Sell Development - Pre Registration                    23
Lease Finance Modification                             18
Portfolio Mortgage Development Modification            11
Delayed Portfolio Mortgage                              8
Lease to Own Registration Pre-Registration              6
Modify Delayed Mortgage                                 6
Adding Land By Sell                                     4
Lease to Own on Development Registration                4
Mortgage Transfer                                       3
Delayed Sell Development                                2
Modify Mortgage Pre-Registration                        1
Lease to Own on Development Modification                1
Name: count, dtype: int64

--- IS_OFFPLAN_EN ---
IS_OFFPLAN_EN
Off-Plan    78091
Ready       70500
Name: count, dtype: int64

--- IS_FREE_HOLD_EN ---
IS_FREE_HOLD_EN
Free Hold        141737
Non Free Hold      6854
Name: count, dtype: int64

--- USAGE_EN ---
USAGE_EN
Residential    143808
Commercial       4783
Name: count, dtype: int64

--- PROP_TYPE_EN ---
PROP_TYPE_EN
Unit        118476
Land         17385
Building     12730
Name: count, dtype: int64

--- PROP_SB_TYPE_EN ---
PROP_SB_TYPE_EN
Flat                                  109574
Villa                                  12922
Residential                             7768
Commercial                              4491
Office                                  4333
Hotel Apartment                         2198
NaN                                     1886
Shop                                    1568
General Use                              775
Hotel Rooms                              752
Residential / Residential Villa          601
Land                                     341
Airport                                  303
Government Housing                       253
Residential Flats                        225
Industrial                               214
Residential / Villas                     145
Labor Camp                                51
Residential / Attached Villas             41
Unit                                      27
Sports Club                               20
Agricultural                              14
Workshop                                  14
Warehouse                                 14
Stacked Townhouses                        13
Building                                  11
Show Rooms                                 9
School                                     7
Sized Partition                            4
Hotel                                      3
Shopping Mall                              2
Hospital                                   2
Commercial / Offices / Residential         2
Petrol Station                             2
Exhbition Center                           2
Clinic                                     2
Health Club                                1
Gymnasium                                  1
Name: count, dtype: int64

In [35]:
categorical_cols = df.select_dtypes(include="object").columns

C:\Users\gagan\AppData\Local\Temp\ipykernel_40252\3906971751.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [36]:
df[categorical_cols].nunique().sort_values(ascending=False)

TRANSACTION_NUMBER     143955
INSTANCE_DATE          141659
PARKING                 14958
PROJECT_EN               2986
AREA_EN                   272
NEAREST_METRO_EN           55
PROCEDURE_EN               39
PROP_SB_TYPE_EN            37
ROOMS_EN                   13
NEAREST_LANDMARK_EN        13
MASTER_PROJECT_EN          10
NEAREST_MALL_EN             5
GROUP_EN                    3
PROP_TYPE_EN                3
IS_FREE_HOLD_EN             2
IS_OFFPLAN_EN               2
USAGE_EN                    2
dtype: int64

In [37]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
TRANS_VALUE,148591.0,3.523551e+06,3.627088e+07,163.35,814777.00,1407810.80,2711040.00,1.034807e+10
PROCEDURE_AREA,148587.0,4.136656e+02,2.450779e+04,0.75,58.16,84.50,144.04,6.718307e+06
ACTUAL_AREA,148591.0,4.985328e+02,3.218817e+04,6.55,59.41,85.39,144.36,6.718634e+06
TOTAL_BUYER,148591.0,0.000000e+00,0.000000e+00,0.00,0.00,0.00,0.00,0.000000e+00
TOTAL_SELLER,148591.0,0.000000e+00,0.000000e+00,0.00,0.00,0.00,0.00,0.000000e+00

In [38]:
df.nlargest(10, "TRANS_VALUE")[
    [
        "TRANSACTION_NUMBER",
        "INSTANCE_DATE",
        "GROUP_EN",
        "PROCEDURE_EN",
        "TRANS_VALUE",
        "ACTUAL_AREA",
        "AREA_EN",
        "PROP_TYPE_EN",
        "PROP_SB_TYPE_EN",
        "PROJECT_EN"
    ]
]

,TRANSACTION_NUMBER,INSTANCE_DATE,GROUP_EN,PROCEDURE_EN,TRANS_VALUE,ACTUAL_AREA,AREA_EN,PROP_TYPE_EN,PROP_SB_TYPE_EN,PROJECT_EN
129253,39-66-2026,2026-01-28 11:14:00,Mortgage,Development Mortgage,1.034807e+10,1185056.87,DUBAI WATER FRONT,Land,Commercial,NaN
118191,13-385-2026,2026-01-06 15:39:24,Mortgage,Mortgage Registration,4.250000e+09,47506.29,PALM JUMEIRAH,Land,Commercial,NaN
140615,460-53-2026,2026-01-23 21:04:05,Sales,Sale On Payment Plan,3.130255e+09,621815.53,Al Rowaiyah First,Land,NaN,Tilal Binghatti
125004,14-677-2026,2026-05-13 16:39:45,Mortgage,Modify Mortgage,2.594830e+09,1706068.25,Al Yufrah 1,Land,Commercial,NaN
120473,13-6126-2026,2026-02-26 10:31:31,Mortgage,Mortgage Registration,1.750000e+09,31175.18,Marsa Dubai,Land,Commercial,"The Residences, Al Habtoor Grand"
94327,11-3159-2026,2026-01-23 23:12:55,Sales,Sale,1.713544e+09,167375.99,Al Rowaiyah First,Land,NaN,Greenz By Danube
115734,13-2281-2026,2026-01-23 23:14:20,Mortgage,Mortgage Registration,1.713544e+09,167375.99,Al Rowaiyah First,Land,NaN,Greenz By Danube
140616,460-54-2026,2026-01-23 21:01:01,Sales,Sale On Payment Plan,1.461866e+09,290395.17,Al Rowaiyah First,Land,NaN,NaN
131631,41-2665-2026,2026-02-11 12:38:36,Sales,Delayed Sell,1.426328e+09,1088060.04,Al Yelayiss 1,Land,NaN,NaN
125566,152-2-2026,2026-05-19 08:31:45,Mortgage,Portfolio Mortgage Development Modification,1.311384e+09,6718633.78,Saih Aldahal,Land,Government Housing,NaN

In [39]:
(df[[
    "TRANS_VALUE",
    "PROCEDURE_AREA",
    "ACTUAL_AREA"
]] <= 0).sum()

TRANS_VALUE       0
PROCEDURE_AREA    0
ACTUAL_AREA       0
dtype: int64

In [40]:
df["PRICE_PER_SQM"] = df["TRANS_VALUE"] / df["ACTUAL_AREA"]

df["PRICE_PER_SQM"].describe()

count    1.485910e+05
mean     1.873712e+04
std      1.330045e+04
min      1.905623e+00
25%      1.253616e+04
50%      1.718138e+04
75%      2.218777e+04
max      2.207993e+06
Name: PRICE_PER_SQM, dtype: float64

In [41]:
df.nsmallest(10, "PRICE_PER_SQM")[
    [
        "TRANSACTION_NUMBER",
        "GROUP_EN",
        "PROCEDURE_EN",
        "TRANS_VALUE",
        "ACTUAL_AREA",
        "PRICE_PER_SQM",
        "AREA_EN",
        "PROP_TYPE_EN",
        "PROP_SB_TYPE_EN",
        "PROJECT_EN"
    ]
]

,TRANSACTION_NUMBER,GROUP_EN,PROCEDURE_EN,TRANS_VALUE,ACTUAL_AREA,PRICE_PER_SQM,AREA_EN,PROP_TYPE_EN,PROP_SB_TYPE_EN,PROJECT_EN
90162,11-23384-2026,Sales,Sale,163.35,85.72,1.905623,DUBAI MARINA,Unit,Flat,PRINCESS TOWER
79606,11-13620-2026,Sales,Sale,89125.08,25274.34,3.526307,Al Khawaneej Second,Land,Agricultural,NaN
124039,133-272-2026,Sales,Development Registration,51958.00,4827.24,10.763500,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124041,133-274-2026,Sales,Development Registration,65672.00,6101.14,10.763890,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124049,133-282-2026,Sales,Development Registration,92161.00,8562.04,10.763907,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124044,133-277-2026,Sales,Development Registration,111869.00,10392.97,10.763911,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124046,133-279-2026,Sales,Development Registration,42373.00,3936.58,10.763912,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124042,133-275-2026,Sales,Development Registration,77441.00,7194.50,10.763917,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124043,133-276-2026,Sales,Development Registration,77383.00,7189.07,10.763979,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124038,133-271-2026,Sales,Development Registration,42374.00,3936.64,10.764002,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN

In [42]:
df.nlargest(10, "PRICE_PER_SQM")[
    [
        "TRANSACTION_NUMBER",
        "GROUP_EN",
        "PROCEDURE_EN",
        "TRANS_VALUE",
        "ACTUAL_AREA",
        "PRICE_PER_SQM",
        "AREA_EN",
        "PROP_TYPE_EN",
        "PROP_SB_TYPE_EN",
        "PROJECT_EN"
    ]
]

,TRANSACTION_NUMBER,GROUP_EN,PROCEDURE_EN,TRANS_VALUE,ACTUAL_AREA,PRICE_PER_SQM,AREA_EN,PROP_TYPE_EN,PROP_SB_TYPE_EN,PROJECT_EN
123997,133-228-2026,Sales,Development Registration,1.000000e+08,45.29,2.207993e+06,SILICON OASIS,Unit,Flat,Selicon Star 2
124826,14-505-2026,Mortgage,Modify Mortgage,1.718724e+08,115.62,1.486528e+06,BUSINESS BAY,Unit,Office,THE EXCHANGE
124045,133-278-2026,Sales,Development Registration,1.000000e+08,117.94,8.478888e+05,SILICON OASIS,Unit,Flat,Selicon Star 2
124109,133-477-2025,Sales,Development Registration,3.826770e+07,57.01,6.712454e+05,DUBAI INVESTMENT PARK FIRST,Unit,Shop,NaN
32717,102-39311-2026,Sales,Sell - Pre registration,1.176556e+08,222.91,5.278164e+05,Marsa Dubai,Unit,Flat,The Residences at the Dubai Beach Edition
83038,11-16803-2026,Sales,Sale,1.100000e+09,2322.58,4.736112e+05,Trade Center First,Land,Commercial,NaN
124445,14-135-2020,Mortgage,Modify Mortgage,3.000000e+07,76.08,3.943218e+05,AL FURJAN,Land,Commercial,Azizi Samia Residence
74669,102-9383-2026,Sales,Sell - Pre registration,2.699100e+07,76.36,3.534704e+05,BUSINESS BAY,Unit,Flat,One by Binghatti
99014,11-7491-2026,Sales,Sale,3.200000e+08,929.03,3.444453e+05,Trade Center Second,Land,Commercial,NaN
107463,13-14077-2026,Mortgage,Mortgage Registration,7.700000e+08,2322.58,3.315279e+05,Trade Center First,Land,Commercial,NaN

In [43]:
df.nsmallest(10, "PRICE_PER_SQM")[
    [
        "TRANSACTION_NUMBER",
        "GROUP_EN",
        "PROCEDURE_EN",
        "TRANS_VALUE",
        "ACTUAL_AREA",
        "PRICE_PER_SQM",
        "AREA_EN",
        "PROP_TYPE_EN",
        "PROP_SB_TYPE_EN",
        "PROJECT_EN"
    ]
]

,TRANSACTION_NUMBER,GROUP_EN,PROCEDURE_EN,TRANS_VALUE,ACTUAL_AREA,PRICE_PER_SQM,AREA_EN,PROP_TYPE_EN,PROP_SB_TYPE_EN,PROJECT_EN
90162,11-23384-2026,Sales,Sale,163.35,85.72,1.905623,DUBAI MARINA,Unit,Flat,PRINCESS TOWER
79606,11-13620-2026,Sales,Sale,89125.08,25274.34,3.526307,Al Khawaneej Second,Land,Agricultural,NaN
124039,133-272-2026,Sales,Development Registration,51958.00,4827.24,10.763500,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124041,133-274-2026,Sales,Development Registration,65672.00,6101.14,10.763890,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124049,133-282-2026,Sales,Development Registration,92161.00,8562.04,10.763907,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124044,133-277-2026,Sales,Development Registration,111869.00,10392.97,10.763911,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124046,133-279-2026,Sales,Development Registration,42373.00,3936.58,10.763912,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124042,133-275-2026,Sales,Development Registration,77441.00,7194.50,10.763917,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124043,133-276-2026,Sales,Development Registration,77383.00,7189.07,10.763979,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN
124038,133-271-2026,Sales,Development Registration,42374.00,3936.64,10.764002,DUBAI INVESTMENT PARK FIRST,Land,Commercial,NaN

In [44]:
df.shape

(148591, 23)

In [45]:
df.duplicated().sum()

np.int64(190)

In [46]:
df[df.duplicated(keep=False)].sort_values("TRANSACTION_NUMBER").head(20)

,TRANSACTION_NUMBER,INSTANCE_DATE,GROUP_EN,PROCEDURE_EN,IS_OFFPLAN_EN,IS_FREE_HOLD_EN,USAGE_EN,AREA_EN,PROP_TYPE_EN,PROP_SB_TYPE_EN,...,ROOMS_EN,PARKING,NEAREST_METRO_EN,NEAREST_MALL_EN,NEAREST_LANDMARK_EN,TOTAL_BUYER,TOTAL_SELLER,MASTER_PROJECT_EN,PROJECT_EN,PRICE_PER_SQM
8,101-12-2026,2026-07-01 16:12:45,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,HORIZON,Unit,Flat,...,2 B/R,1,Creek Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,BELMORE RESIDENCES,15619.317121
10,101-12-2026,2026-07-01 16:12:45,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,HORIZON,Unit,Flat,...,2 B/R,1,Creek Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,BELMORE RESIDENCES,15619.317121
12,101-12-2026,2026-07-01 16:12:45,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,HORIZON,Unit,Flat,...,2 B/R,1,Creek Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,BELMORE RESIDENCES,15619.317121
13,101-12-2026,2026-07-01 16:12:45,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,HORIZON,Unit,Flat,...,2 B/R,1,Creek Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,BELMORE RESIDENCES,15619.317121
14,101-12-2026,2026-07-01 16:12:45,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,HORIZON,Unit,Flat,...,2 B/R,1,Creek Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,BELMORE RESIDENCES,15619.317121
19,101-14-2026,2026-07-07 09:54:50,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,HORIZON,Unit,Flat,...,1 B/R,1,Creek Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,CLAYDON HOUSE BY ELLINGTON,20622.831936
24,101-14-2026,2026-07-07 09:54:50,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,HORIZON,Unit,Flat,...,1 B/R,1,Creek Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,CLAYDON HOUSE BY ELLINGTON,20622.831936
34,101-15-2026,2026-07-03 09:22:23,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,DUBAI HILLS,Unit,Flat,...,1 B/R,1,First Abu Dhabi Bank Metro Station,Mall of the Emirates,Global Village,0,0,NaN,ELLINGTON HOUSE IV,37241.948751
33,101-15-2026,2026-07-03 09:22:23,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,DUBAI HILLS,Unit,Flat,...,1 B/R,1,First Abu Dhabi Bank Metro Station,Mall of the Emirates,Global Village,0,0,NaN,ELLINGTON HOUSE IV,37241.948751
99,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,10708.603598
106,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,10708.603598
104,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,13993.283224
103,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,13261.594423
102,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,13993.283224
101,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,13261.594423
100,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,13993.283224
98,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,13261.594423
94,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,10708.603598
96,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,13261.594423
95,101-3-2026,2026-03-23 14:53:48,Mortgage,Portfolio Mortgage Registration Pre-Registration,Off-Plan,Free Hold,Residential,BUSINESS BAY,Unit,Flat,...,1 B/R,1,Business Bay Metro Station,Dubai Mall,Downtown Dubai,0,0,NaN,WEST BAY TOWER,13993.283224

In [47]:
df.duplicated().sum()

np.int64(190)

In [48]:
df = df.drop_duplicates().copy()

In [49]:
df.duplicated().sum()

np.int64(0)

In [50]:
df.shape

(148401, 23)

In [53]:
df.isna().sum().sort_values(ascending = False)

MASTER_PROJECT_EN      147876
NEAREST_MALL_EN         78038
NEAREST_METRO_EN        76391
NEAREST_LANDMARK_EN     57780
PARKING                 32833
ROOMS_EN                21117
PROJECT_EN              18889
PROP_SB_TYPE_EN          1886
PROCEDURE_AREA              4
IS_OFFPLAN_EN               0
IS_FREE_HOLD_EN             0
GROUP_EN                    0
INSTANCE_DATE               0
TRANSACTION_NUMBER          0
PROCEDURE_EN                0
USAGE_EN                    0
AREA_EN                     0
PROP_TYPE_EN                0
TRANS_VALUE                 0
ACTUAL_AREA                 0
TOTAL_BUYER                 0
TOTAL_SELLER                0
PRICE_PER_SQM               0
dtype: int64

In [54]:
df = df.drop(columns=["MASTER_PROJECT_EN"])

In [55]:
df.shape

(148401, 22)

In [56]:
df[df["ROOMS_EN"].isna()]["PROP_SB_TYPE_EN"].value_counts(dropna=False)

PROP_SB_TYPE_EN
Residential                           7766
Commercial                            4491
Office                                2386
NaN                                   1886
Shop                                  1303
General Use                            775
Residential / Residential Villa        601
Land                                   341
Airport                                296
Government Housing                     253
Residential Flats                      225
Industrial                             214
Villa                                  203
Residential / Villas                   145
Labor Camp                              51
Residential / Attached Villas           41
Unit                                    27
Sports Club                             20
Agricultural                            14
Workshop                                14
Warehouse                               14
Building                                11
Show Rooms                               7
School                                   7
Flat                                     4
Sized Partition                          4
Hotel                                    2
Hotel Apartment                          2
Shopping Mall                            2
Hospital                                 2
Commercial / Offices / Residential       2
Petrol Station                           2
Exhbition Center                         2
Clinic                                   2
Health Club                              1
Gymnasium                                1
Name: count, dtype: int64

In [57]:
df[
    (df["ROOMS_EN"].isna()) &
    (df["PROP_SB_TYPE_EN"].isin([
        "Flat",
        "Villa",
        "Residential",
        "Residential Flats"
    ]))
]["PROP_SB_TYPE_EN"].value_counts()

PROP_SB_TYPE_EN
Residential          7766
Residential Flats     225
Villa                 203
Flat                    4
Name: count, dtype: int64

In [58]:
df["ROOMS_EN"].value_counts(dropna=False)

ROOMS_EN
1 B/R        45430
Studio       31627
2 B/R        28145
NaN          21117
3 B/R        11355
4 B/R         6678
Office        1946
5 B/R         1710
Shop           270
6 B/R           71
PENTHOUSE       36
7 B/R           13
9 B/R            2
Hotel            1
Name: count, dtype: int64

In [59]:
categorical_missing_cols = [
    "ROOMS_EN",
    "PARKING",
    "NEAREST_METRO_EN",
    "NEAREST_MALL_EN",
    "NEAREST_LANDMARK_EN",
    "PROJECT_EN",
    "PROP_SB_TYPE_EN"
]

df[categorical_missing_cols] = df[categorical_missing_cols].fillna("Unknown")

In [60]:
df[categorical_missing_cols].isna().sum()

ROOMS_EN               0
PARKING                0
NEAREST_METRO_EN       0
NEAREST_MALL_EN        0
NEAREST_LANDMARK_EN    0
PROJECT_EN             0
PROP_SB_TYPE_EN        0
dtype: int64

In [61]:
df[df["PROCEDURE_AREA"].isna()][
    ["PROCEDURE_AREA", "ACTUAL_AREA", "TRANS_VALUE", "AREA_EN", "PROP_TYPE_EN"]
]

        PROCEDURE_AREA  ACTUAL_AREA   TRANS_VALUE         AREA_EN PROP_TYPE_EN
93696              NaN        70.14  1.480000e+06      THE GREENS         Unit
125566             NaN   6718633.78  1.311384e+09    Saih Aldahal         Land
125567             NaN   4478819.00  1.311384e+09    Saih Aldahal         Land
137096             NaN       187.94  3.645455e+06  BARSHA HEIGHTS         Unit

In [62]:
df["PROCEDURE_AREA"].isna().sum()

np.int64(4)

In [63]:
df.isna().sum().sort_values(ascending=False).head(10)

PROCEDURE_AREA        4
TRANSACTION_NUMBER    0
GROUP_EN              0
PROCEDURE_EN          0
IS_OFFPLAN_EN         0
INSTANCE_DATE         0
IS_FREE_HOLD_EN       0
USAGE_EN              0
PROP_TYPE_EN          0
AREA_EN               0
dtype: int64

In [64]:
df["PROCEDURE_AREA"] = df["PROCEDURE_AREA"].fillna(df["ACTUAL_AREA"])

In [65]:
df["PROCEDURE_AREA"].isna().sum()

np.int64(0)

In [66]:
df.isna().sum().sort_values(ascending=False).head(10)

TRANSACTION_NUMBER    0
INSTANCE_DATE         0
GROUP_EN              0
PROCEDURE_EN          0
IS_OFFPLAN_EN         0
IS_FREE_HOLD_EN       0
USAGE_EN              0
AREA_EN               0
PROP_TYPE_EN          0
PROP_SB_TYPE_EN       0
dtype: int64

In [67]:
df.isna().sum().sum()

np.int64(0)

In [69]:
df["INSTANCE_DATE"] = pd.to_datetime(df["INSTANCE_DATE"])

In [70]:
df["INSTANCE_DATE"].dtype

dtype('<M8[us]')

In [71]:
df["YEAR"] = df["INSTANCE_DATE"].dt.year
df["MONTH"] = df["INSTANCE_DATE"].dt.month
df["DAY_OF_WEEK"] = df["INSTANCE_DATE"].dt.dayofweek

In [72]:
df[["INSTANCE_DATE", "YEAR", "MONTH", "DAY_OF_WEEK"]].head()

        INSTANCE_DATE  YEAR  MONTH  DAY_OF_WEEK
0 2026-07-01 16:00:21  2026      7            2
1 2026-07-01 16:00:21  2026      7            2
2 2026-07-01 16:00:21  2026      7            2
3 2026-07-01 16:00:21  2026      7            2
4 2026-07-01 16:29:02  2026      7            2

In [73]:
df[["TRANS_VALUE", "ACTUAL_AREA", "PRICE_PER_SQM"]].head()

   TRANS_VALUE  ACTUAL_AREA  PRICE_PER_SQM
0   1699451.22        46.17   36808.560104
1   1699451.22        99.32   17110.866089
2   1699451.22        91.81   18510.524126
3   1699451.22        46.15   36824.511809
4   6608107.80       535.68   12335.924059

In [74]:
df = df.drop(columns=[
    "TRANSACTION_NUMBER",
    "INSTANCE_DATE",
    "TOTAL_BUYER",
    "TOTAL_SELLER"
])

In [75]:
df.shape

(148401, 21)

In [76]:
df.columns

Index(['GROUP_EN', 'PROCEDURE_EN', 'IS_OFFPLAN_EN', 'IS_FREE_HOLD_EN',
       'USAGE_EN', 'AREA_EN', 'PROP_TYPE_EN', 'PROP_SB_TYPE_EN', 'TRANS_VALUE',
       'PROCEDURE_AREA', 'ACTUAL_AREA', 'ROOMS_EN', 'PARKING',
       'NEAREST_METRO_EN', 'NEAREST_MALL_EN', 'NEAREST_LANDMARK_EN',
       'PROJECT_EN', 'PRICE_PER_SQM', 'YEAR', 'MONTH', 'DAY_OF_WEEK'],
      dtype='str')

In [77]:
categorical_cols = df.select_dtypes(include="object").columns
categorical_cols

C:\Users\gagan\AppData\Local\Temp\ipykernel_40252\3430876840.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

Index(['GROUP_EN', 'PROCEDURE_EN', 'IS_OFFPLAN_EN', 'IS_FREE_HOLD_EN',
       'USAGE_EN', 'AREA_EN', 'PROP_TYPE_EN', 'PROP_SB_TYPE_EN', 'ROOMS_EN',
       'PARKING', 'NEAREST_METRO_EN', 'NEAREST_MALL_EN', 'NEAREST_LANDMARK_EN',
       'PROJECT_EN'],
      dtype='str')

In [78]:
categorical_cols = df.select_dtypes(include="str").columns

In [79]:
numerical_cols = df.select_dtypes(include="number").columns
numerical_cols

Index(['TRANS_VALUE', 'PROCEDURE_AREA', 'ACTUAL_AREA', 'PRICE_PER_SQM', 'YEAR',
       'MONTH', 'DAY_OF_WEEK'],
      dtype='str')

In [80]:
y = df["TRANS_VALUE"]

In [81]:
X = df.drop(columns=["TRANS_VALUE", "PRICE_PER_SQM"])
y = df["TRANS_VALUE"]

In [82]:
print(X.shape)
print(y.shape)

(148401, 19)
(148401,)

In [83]:
df.to_csv("../data/processed/cleaned_transactions.csv", index=False)

In [84]:
import os

os.path.exists("../data/processed/cleaned_transactions.csv")

True